name: mrdc-project
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - babel=2.11.0
  - bcrypt=3.2.0
  - blas=1.0
  - boto3=1.29.1
  - botocore=1.32.1
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - colour=0.1.5
  - cryptography=41.0.7
  - dbus=1.13.18
  - distro=1.8.0
  - expat=2.5.0
  - freetype=2.12.1
  - furl=2.1.2
  - glib=2.69.1
  - greenlet=3.0.1
  - idna=3.4
  - infinity=1.5
  - intel-openmp=2023.1.0
  - intervals=0.9.2
  - jmespath=1.0.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.39
  - libpq=12.15
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.15
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.2
  - numpy-base=1.26.2
  - openjdk=11.0.13
  - openssl=3.0.12
  - orderedmultidict=1.0.1
  - pandas=2.1.4
  - passlib=1.7.4
  - pcre=8.45
  - pendulum=2.1.2
  - phonenumbers=8.12.27
  - pip=23.3.1
  - psycopg2=2.9.3
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pytzdata=2020.1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - s3transfer=0.7.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlalchemy=2.0.21
  - sqlalchemy-utils=0.41.1
  - sqlite=3.41.2
  - tabula-py=2.6.0
  - tbb=2021.8.0
  - tk=8.6.12
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - zlib=1.2.13
