CREATE TABLE IF NOT EXISTS dim_products (
	index SERIAL UNIQUE NOT NULL PRIMARY KEY,
    product_name VARCHAR(250) NOT NULL,
    product_price BIGINT NOT NULL,
	weight INTEGER NOT NULL,
	category VARCHAR(250) NOT NULL,
    EAN INTEGER NOT NULL,
	date_added DATE NOT NULL CHECK (date_added < NOW()),
	uuid  UUID(150) UNIQE NOT NULL,
    removed VARCHAR(100) NOT NULL,
	product_code VARCHAR(50) UNIQUE NOT NULL
);