CREATE TABLE IF NOT EXISTS dim_date_times (
	index SERIAL UNIQUE NOT NULL PRIMARY KEY,
    timestamp DATE NOT NULL,
    month SMALLINT NOT NULL,
	year SMALLINT NOT NULL,
	day SMALLINT NOT NULL,
    time_period VARCHAR(50) UNIQUE NOT NULL,
	date_uuid UUID UNIQUE NOT NULL
);